### ISSUE TITLE
There doesn't seem to be a way to change the "normal" mode keybinding

### ISSUE THREAD

**Issue by Richiban** [DnailZ/oomotion_vscode#5]
I'm sure the usual shortcut of `J K` works well for most people, but for those of us who don't use QWERTY (e.g. me on Colemak) it's _super_ awkward. Where can I change this setting? It doesn't appear in the list of keybindings.

**Comment by Richiban** [comment]
If this isn't going to be configurable, can we at least have a normal VS code command to switch to normal mode so that we could introduce our own keybinding?

Many thanks!

**Comment by DnailZ** [comment]
OK, current GitHub version now has a `oomotion.gotoNormalKeybinding` option, you can use `"oomotion.gotoNormalKeybinding": "jk"` to configure what keys you want to go back to NORMAL state.

**Comment by sapjax** [comment]
> OK, current GitHub version now has a `oomotion.gotoNormalKeybinding` option, you can use `"oomotion.gotoNormalKeybinding": "jk"` to configure what keys you want to go back to NORMAL state.

The vscode marketplace version seems not updated, can you publish it? thanks!
